dictionaries = [
    "en_us",
    "en_gb",
    "pl",
]
words = [
    "argmax",
    "bayesa",
    "bayesowskiego",
    "epanechnikov",
    "epanecznika",
    "epańczykowa",
    "gaussowska",
    "gaussowski",
    "gaussowskie",
    "gaussowskiego",
    "gaussowskim",
    "gradientowo",
    "hiperparametrem",
    "hiperparametrów",
    "konwolucyjne",
    "laplasjańska",
    "laplasjańskie",
    "laplasjańskiego",
    "multikwadratowa",
    "multiquadric",
    "overfitting",
    "pnn",
    "probablistycznej",
    "silvermana",
    "spambase",
    "underfitting",
    "walidacyjnym",
    "zaszumionych",
]
ignore_patterns = ["<.*?>"]
